const OFFICE_START_TIME = "10:00";
const OFFICE_END_TIME = "19:00";
const LATE_THRESHOLD_TIME = "10:10";
const DEFAULT_LEAVE_BALANCE = 12;
const DEFAULT_PASSWORD = "changeme123";
const DEFAULT_JWT_EXPIRES_IN = "8h";

module.exports = {
  OFFICE_START_TIME,
  OFFICE_END_TIME,
  LATE_THRESHOLD_TIME,
  DEFAULT_LEAVE_BALANCE,
  DEFAULT_PASSWORD,
  DEFAULT_JWT_EXPIRES_IN,
};
